 set lines 180 pages 200
col EXTERNAL_USERID for a20
col DBLINK_INFO for a30
col ACTION_NAME for a8
col DBUSERNAME for a15
COL USERNAME FOR A20
col USERHOST for a35
col EVENT_TIMESTAMP for a30
col OS_USERNAME for a15
col RETURN_CODE for 99999999
col CLIENT_PROGRAM_NAME for a25
col TERMINAL for a20
ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-YY HH24:MI';
select EVENT_TIMESTAMP,OLS_POLICY_NAME , OS_USERNAME, USERHOST, TERMINAL, DBUSERNAME, DBPROXY_USERNAME, EXTERNAL_USERID, GLOBAL_USERID, CLIENT_PROGRAM_NAME, DBLINK_INFO, ACTION_NAME, RETURN_CODE  from UNIFIED_AUDIT_TRAIL where return_code IN ('1017','2004') order by 1;
